<?php
namespace skillio\core\routing;

use EMethods;
use skillio\controllers\MainController;
use skillio\core\interfaces\IMiddleware;
use skillio\core\internal\exceptions\InternalException;
use skillio\core\internal\RestrictedAccessFactory;
use skillio\core\languages\Lang;
use skillio\core\routing\validation\Validator;
use skillio\core\Session;
use skillio\core\utils\content\View;

/**
 * Class Route
 * Represents a route in the application.
 *
 * @package skillio\core\routing
 */
class Route
{
    /** @var string|null The name of the route. */
    private ?string $name = null;

    /** @var string The URL for the route. */
    private string $url;

    /** @var array The HTTP methods for the route. */
    private array $methods;

    /** @var callable|array<int,Controller> The callback to be executed when the route is matched. */
    private mixed $callback;

    /** @var IMiddleware[] Middlewares to be applied to the route. */
    private array $middlewares;

    /** @var string The pattern for route parameters. */
    private const string PARAM_PATTERN = "/{([\w]+)}/";

    /**
     * Get the name of the route.
     *
     * @return string|null The name of the route, or null if not set.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Check if the route has a name.
     *
     * @return bool True if the route has a name, false otherwise.
     */
    public function hasName(): bool
    {
        return $this->name !== null;
    }

    /**
     * Get the URL for the route.
     *
     * @return string The URL for the route.
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * Set the URL for the route.
     *
     * @param string $url The URL to set for the route.
     */
    public function setUrl(string $url): void
    {
        // Set the URL for the route
        $this->url = $url;
    }

    /**
     * Get the HTTP methods for the route.
     *
     * @return array The HTTP methods for the route.
     */
    public function getMethods(): array
    {
        return $this->methods;
    }

    /**
     * Get the callback to be executed when the route is matched.
     *
     * @return callable|array The callback for the route.
     */
    public function getCallback(): mixed
    {
        return $this->callback;
    }

    /**
     * Set the callback for the route.
     *
     * @param callable|array $callback The callback to set for the route.
     */
    public function setController(mixed $controller): void
    {
        // Set the controller for the route
        $this->callback = [$controller, $this->callback[1] ?? $this->callback[0]];
    }

    /**
     * Set the middlewares for the route.
     *
     * @param Middleware[] $middlewares The middlewares to set for the route.
     */
    public function setMiddlewares(array $middlewares): void
    {
        // Set the middlewares for the route
        $this->middlewares = $middlewares;
    }

    /**
     * Route constructor.
     *
     * @param string $url The URL for the route.
     * @param array $methods The HTTP methods for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    private function __construct(string $url, array $methods, callable|array $callback)
    {
        // Initialize the route with the provided URL, methods, and callback
        if (Lang::isIntegratedLanguagesActive())
            $url = "/" . Lang::PARAM_NAME . $url;
        
        $this->url = $url;
        $this->methods = $methods;
        $this->callback = $callback;
        $this->middlewares = [];
    }

    /**
     * Get the handler for the route.
     *
     * @return callable The handler for the route.
     * @throws InternalException If the callback is not callable or not an array with controller and method.
     */
    public function getHandler(): callable
    {
        // If the callback is a callable, return it directly
        $originalHandler = $this->getOriginalHandler();

        // Loop through the middlewares and wrap the original handler
        foreach ($this->middlewares as $middleware) 
        {
            $next = $originalHandler;
            $middleware = new $middleware();
            $originalHandler = fn (Request $request): Response => $middleware->handle($request, $next);
        }

        /**
         * Wrap the original handler to ensure it returns a Response instance.
         * @param Request $request The incoming request.
         * @return Response The response generated by the original handler.
         */
        return function (Request $request) use ($originalHandler) : Response
        {
            // Call the original handler with the request
            $response = $originalHandler($request);
            $content = $response->getContent();

            if($_ENV["API"] === "true")
                $response->addHeader(name: "Content-Type", value: "application/json");
            else
            {
                // Set automated handling contexts for the page
                if(Lang::isIntegratedLanguagesActive()) 
                { 
                    $content->with(
                    data: [
                        "availableLanguages" => Lang::getAvailableLanguages(),
                        "lang" => $request->getQueryParams()->get("lang")
                    ]);

                    $content->js(name: "lang");
                }

                // Set the global data for the view
                $content->with(data: MainController::globalData(request: $request));
                
                // Extract the session validation data if available
                $validator = Validator::getInstance();
                if($validator->isSaved())
                    $validator->saveToSession();
                else
                {
                    $dataValidation = Session::extractAt("dataValidation");
                    $lang = Lang::getLanguage(lang: $request->getQueryParams()->get("lang", Lang::getDefaultLanguage()));
                    $fieldsTranslations = $lang->get("fieldValidations");
                    
                    // In array [value, error] replace the error with the translation
                    if($dataValidation)
                        $dataValidation = array_map(
                            function($value) use ($fieldsTranslations)
                            {
                                if(isset($value["error"]) && isset($fieldsTranslations[$value["error"]]))
                                    $value["error"] = $fieldsTranslations[$value["error"]];
                                
                                return $value;
                            }, 
                            $dataValidation
                        );

                    $content->with(
                        data: ["dataValidation" => $dataValidation]
                    );
                }
            }

            return $response;
        };
    }

    /**
     * Get the original handler for the route.
     *
     * @return callable(Request $request):Response The original handler for the route.
     * @throws InternalException If the callback is not callable or not an array with controller and method.
     */
    private function getOriginalHandler(): callable
    {
        if (is_callable($this->callback))
            return $this->callback;
        else if (is_array($this->callback) && isset($this->callback[0]) && isset($this->callback[1]))
        {
            // If the callback is an array with controller and method, instantiate the controller and call the method
            $controller = $this->callback[0];
            if (!class_exists($controller))
                new InternalException("Controller '$controller' does not exist");

            $method = $this->callback[1];
            if (!method_exists($controller, $method))
                new InternalException("Method '$method' not found in controller '$controller'");

            // Create an instance of the controller and return a callable for the method
            $controllerInstance = new $controller();
            return fn(Request $request) => $controllerInstance->$method($request);
        }
        else
            throw new InternalException("The route callback must be a callable or an array with 'controller' and 'method' keys, got: " . gettype($this->callback));
    }
    
    /**
     * Get the link for the route with optional parameters.
     *
     * @param array<string,mixed> $params The parameters to replace in the URL.
     * @return string The generated link for the route.
     */
    public function link(array $params = []): string
    {
        // If the the language is integrated, add the language parameter to the params array
        if (Lang::isIntegratedLanguagesActive())
            $params["lang"] = Request::getInstance()?->getQueryParams()->get("lang") ?? Lang::getDefaultLanguage();

        // return the URL with the query parameters in the format {lang}/home => /en/home
        $url = $this->getUrl();
        
        $url = preg_replace_callback(
            pattern: self::PARAM_PATTERN,
            callback: fn(array $matches) => $params[$matches[1]] ?? "",
            subject: $url
        );
        
        return $url;
    }

    /**
     * Set the name of the route.
     *
     * @param string $name The name to set for the route.
     * @return self The current instance of Route.
     */
    public function name(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Creates a new route instance.
     *
     * @param string $url The URL for the route.
     * @param string $method The HTTP method for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    public static function get(string $url, callable|array $callback) : self
    {
        $route = new self(url: $url, methods: ['GET'], callback: $callback);
        Router::addRoute(route: $route);

        return $route;
    }

    /**
     * Creates a new route instance for POST requests.
     *
     * @param string $url The URL for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    public static function post(string $url, callable|array $callback) : self
    {
        $route = new self(url: $url, methods: ['POST'], callback: $callback);
        Router::addRoute(route: $route);

        return $route;
    }

    /**
     * Creates a new route instance for PUT requests.
     *
     * @param string $url The URL for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    public static function put(string $url, callable|array $callback) : self
    {
        $route = new self(url: $url, methods: ['PUT'], callback: $callback);
        Router::addRoute(route: $route);

        return $route;
    }
    
    /**
     * Creates a new route instance for PATCH requests.
     *
     * @param string $url The URL for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    public static function patch(string $url, callable|array $callback) : self
    {
        $route = new self(url: $url, methods: ['PATCH'], callback: $callback);
        Router::addRoute(route: $route);

        return $route;
    }

    /**
     * Creates a new route instance for DELETE requests.
     *
     * @param string $url The URL for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    public static function delete(string $url, callable|array $callback) : self
    {
        $route = new self(url: $url, methods: ['DELETE'], callback: $callback);
        Router::addRoute(route: $route);

        return $route;
    }

    /**
     * Creates a new route instance that matches multiple HTTP methods.
     *
     * @param array $methods The HTTP methods for the route.
     * @param string $url The URL for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    public static function match(array $methods, string $url, callable|array $callback) : self
    {
        $route = new self(url: $url, methods: $methods, callback: $callback);
        Router::addRoute(route: $route);

        return $route;
    }

    /**
     * Creates a new route instance that matches any HTTP method.
     *
     * @param string $url The URL for the route.
     * @param callable|array $callback The callback to be executed when the route is matched.
     */
    public static function any(string $url, callable|array $callback) : self
    {
        $route = new self(url: $url, methods: EMethods::cases(), callback: $callback);
        Router::addRoute(route: $route);

        return $route;
    }

    /**
     * Creates a new route instance that renders a view.
     *
     * @param string $url The URL for the route.
     * @param View $view The view to be rendered when the route is matched.
     */
    public static function view(string $url, View $view, int $statusCode = 200) : self
    {
        $route = new self(url: $url, methods: ['GET'], callback: fn() => new Response(
            content: $view,
            statusCode: $statusCode,
        ));
        
        Router::addRoute(route: $route);

        return $route;
    }

    /**
     * Creates a new route group.
     *
     * @param mixed $controller The controller for the group.
     * @param array $routes The routes to be added to the group.
     * @return Group The created route group.
     */
    public static function group(mixed $controller, array $routes): Group
    {
        return Group::create(controller: $controller, routes: $routes);
    }

    /**
     * Creates a new middleware instance.
     *
     * @param array $middlewares The middlewares to be applied to the route.
     * @param Route[] $routes The routes to which the middlewares will be applied.
     * @return Middleware The created middleware instance.
     */
    public static function middleware(array $middlewares, array $routes): Middleware
    {
        return Middleware::create(middlewares: array_reverse($middlewares), routes: $routes);
    }
}
?>